// Normalisation (JetPunk-style)
function normalize(str) {
    return str.toLowerCase().replace(/[^a-z0-9]/g, "");
}

// Your station list
const answers = {
    "allawah": "Allawah",
    "arncliffe": "Arncliffe",
    "artarmon": "Artarmon",
    "ashfield": "Ashfield",
    "asquith": "Asquith",
    "auburn": "Auburn",
    "banksia": "Banksia",
    "bankstown": "Bankstown",
    "barangaroo": "Barangaroo",
    "beecroft": "Beecroft",
    "bellavista": "BellaVista",
    "belmore": "Belmore",
    "berala": "Berala",
    "berowra": "Berowra",
    "beverlyhills": "BeverlyHills",
    "bexleynorth": "BexleyNorth",
    "birrong": "Birrong",
    "blacktown": "Blacktown",
    "bondijunction": "BondiJunction",
    "bardwellpark": "BardwellPark",
    "burwood": "Burwood",
    "cabramatta": "Cabramatta",
    "campbelltown": "Campbelltown",
    "campsie": "Campsie",
    "canleyvale": "CanleyVale",
    "canterbury": "Canterbury",
    "caringbah": "Caringbah",
    "carlton": "Carlton",
    "carramar": "Carramar",
    "castlehill": "CastleHill",
    "casula": "Casula",
    "central": "Central",
    "chatswood": "Chatswood",
    "cheltenham": "Cheltenham",
    "cherrybrook": "Cherrybrook",
    "chesterhill": "ChesterHill",
    "circularquay": "CircularQuay",
    "clarendon": "Clarendon",
    "clyde": "Clyde",
    "como": "Como",
    "concordwest": "ConcordWest",
    "cronulla": "Cronulla",
    "crowsnest": "CrowsNest",
    "croydon": "Croydon",
    "denistone": "Denistone",
    "domesticairport": "DomesticAirport",
    "doonside": "Doonside",
    "dulwichhill": "DulwichHill",
    "easthills": "EastHills",
    "eastrichmond": "EastRichmond",
    "eastwood": "Eastwood",
    "edgecliff": "Edgecliff",
    "edmondsonpark": "EdmondsonPark",
    "emuplains": "EmuPlains",
    "engadine": "Engadine",
    "epping": "Epping",
    "erskineville": "Erskineville",
    "fairfield": "Fairfield",
    "flemington": "Flemington",
    "gadigal": "Gadigal",
    "glenfield": "Glenfield",
    "gordon": "Gordon",
    "granville": "Granville",
    "greensquare": "GreenSquare",
    "guildford": "Guildford",
    "gymea": "Gymea",
    "harrispark": "HarrisPark",
    "heathcote": "Heathcote",
    "hillsshowground": "HillsShowground",
    "holsworthy": "Holsworthy",
    "homebush": "Homebush",
    "hornsby": "Hornsby",
    "hurlstonepark": "HurlstonePark",
    "hurstville": "Hurstville",
    "ingleburn": "Ingleburn",
    "internationalairport": "InternationalAirport",
    "jannali": "Jannali",
    "kellyville": "Kellyville",
    "killara": "Killara",
    "kingscross": "KingsCross",
    "kingsgrove": "Kingsgrove",
    "kingswood": "Kingswood",
    "kirrawee": "Kirrawee",
    "kogarah": "Kogarah",
    "lakemba": "Lakemba",
    "leightonfield": "Leightonfield",
    "leppington": "Leppington",
    "leumeah": "Leumeah",
    "lewisham": "Lewisham",
    "lidcombe": "Lidcombe",
    "lindfield": "Lindfield",
    "liverpool": "Liverpool",
    "loftus": "Loftus",
    "macarthur": "Macarthur",
    "macdonaldtown": "Macdonaldtown",
    "macquariefields": "MacquarieFields",
    "macquariepark": "MacquariePark",
    "macquarieuniversity": "MacquarieUniversity",
    "marayong": "Marayong",
    "marrickville": "Marrickville",
    "martinplace": "MartinPlace",
    "mascot": "Mascot",
    "meadowbank": "Meadowbank",
    "merrylands": "Merrylands",
    "milsonspoint": "MilsonsPoint",
    "minto": "Minto",
    "miranda": "Miranda",
    "mortdale": "Mortdale",
    "mountcolah": "MountColah",
    "mountdruitt": "MountDruitt",
    "mountkuringgai": "MountKuringGai",
    "mulgrave": "Mulgrave",
    "museum": "Museum",
    "narwee": "Narwee",
    "newtown": "Newtown",
    "normanhurst": "Normanhurst",
    "northyde": "NorthRyde",
    "northstrathfield": "NorthStrathfield",
    "northsydney": "NorthSydney",
    "norwest": "Norwest",
    "oatley": "Oatley",
    "olympicpark": "OlympicPark",
    "padstow": "Padstow",
    "panania": "Panania",
    "parramatta": "Parramatta",
    "pendlehill": "PendleHill",
    "pennanthills": "PennantHills",
    "penrith": "Penrith",
    "penshurst": "Penshurst",
    "petersham": "Petersham",
    "punchbowl": "Punchbowl",
    "pymble": "Pymble",
    "quakershill": "QuakersHill",
    "redfern": "Redfern",
    "regentspark": "RegentsPark",
    "revesby": "Revesby",
    "rhodes": "Rhodes",
    "richmond": "Richmond",
    "riverstone": "Riverstone",
    "riverwood": "Riverwood",
    "rockdale": "Rockdale",
    "rootyhill": "RootyHill",
    "roseville": "Roseville",
    "rousehill": "RouseHill",
    "schofields": "Schofields",
    "sefton": "Sefton",
    "sevenhills": "SevenHills",
    "stjames": "StJames",
    "stleonards": "StLeonards",
    "stmarys": "StMarys",
    "stpeters": "StPeters",
    "stanmore": "Stanmore",
    "strathfield": "Strathfield",
    "summerhill": "SummerHill",
    "sutherland": "Sutherland",
    "sydenham": "Sydenham",
    "tallawong": "Tallawong",
    "tempe": "Tempe",
    "thornleigh": "Thornleigh",
    "toongabbie": "Toongabbie",
    "townhall": "TownHall",
    "turramurra": "Turramurra",
    "turrella": "Turrella",
    "victoriacross": "VictoriaCross",
    "villawood": "Villawood",
    "vineyard": "Vineyard",
    "wahroonga": "Wahroonga",
    "waitara": "Waitara",
    "warrawee": "Warrawee",
    "warwickfarm": "WarwickFarm",
    "waterfall": "Waterfall",
    "waterloo": "Waterloo",
    "waverton": "Waverton",
    "wentworthville": "Wentworthville",
    "werrington": "Werrington",
    "westryde": "WestRyde",
    "westmead": "Westmead",
    "wileyspark": "WileyPark",
    "windsor": "Windsor",
    "wollicreek": "WolliCreek",
    "wollstonecraft": "Wollstonecraft",
    "woolooware": "Woolooware",
    "wynyard": "Wynyard",
    "yagoona": "Yagoona",
    "yennora": "Yennora"
};

let total = Object.keys(answers).length;
let score = 0;
document.getElementById("score").textContent = `${score} / ${total}`;

document.getElementById("input").addEventListener("input", function () {
    let guess = normalize(this.value);

    if (answers[guess]) {
        let id = answers[guess];
        let el = document.getElementById(id);
        if (el) el.classList.add("correct");
        delete answers[guess];
        score++;
        document.getElementById("score").textContent = `${score} / ${total}`;
        this.value = "";
    }
});